name: Main Branch PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npx tsc --noEmit

  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        if: github.event_name == 'pull_request'
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          REGEX="^(feat|fix|docs|style|refactor|test)\/[a-zA-Z0-9]+$"
          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "Branch name ($BRANCH_NAME) does not match the required format."
            echo "Please rename your branch to follow the convention: <type>/<notion-task-id>"
            exit 1
          fi

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3